//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 12:30:09 PM IST 
//


package com.lexmark.properties.schema.sw.document;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="document_info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="object_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="owner_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="locale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mdmlevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="mdm_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="usernumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="definition_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="schedule_frequency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="file_data_link" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="job_runlog_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="legal_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="isoverwrite" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="a_content_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="acl_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="acl_domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="r_folder_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="r_object_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="a_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="a_last_review_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="r_object_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="keywords">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                             &lt;element name="values" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentInfo"
})
@XmlRootElement(name = "metadata")
public class DocumentProperties {

    @XmlElement(name = "single", required = true)
    protected DocumentProperties.DocumentInfo documentInfo;

    /**
     * Gets the value of the documentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentProperties.DocumentInfo }
     *     
     */
    public DocumentProperties.DocumentInfo getDocumentInfo() {
        return documentInfo;
    }

    /**
     * Sets the value of the documentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentProperties.DocumentInfo }
     *     
     */
    public void setDocumentInfo(DocumentProperties.DocumentInfo value) {
        this.documentInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="object_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="owner_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="locale" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mdmlevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="mdm_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="usernumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="definition_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="schedule_frequency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="file_data_link" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="job_runlog_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="legal_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="isoverwrite" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="a_content_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="acl_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="acl_domain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="r_folder_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="r_object_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="a_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="a_last_review_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="r_object_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="keywords">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *                   &lt;element name="values" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
    	"fileName",
        "objectName",
        "ownerName",
        "locale",
        "mdmlevel",
        "mdmId",
        "usernumber",
        "definitionId",
        "scheduleFrequency",
        "fileDataLink",
        "jobRunlogId",
        "legalName",
        "isoverwrite",
        "aContentType",
        "title",
        "aclName",
        "aclDomain",
        "rFolderPath",
        "rObjectType",
        "aStatus",
        "aLastReviewDate",
        "rObjectId",
        "fileContentDate",
        "keywords"
    })
    public static class DocumentInfo {
    	

 
		@XmlElement(name = "file_name", required = true)
        protected String fileName;
        @XmlElement(name = "object_name", required = true)
        protected String objectName;
        @XmlElement(name = "owner_name", required = true)
        protected String ownerName;
        @XmlElement(required = true)
        protected String locale;
        protected String mdmlevel;
        @XmlElement(name = "mdm_id")
        protected String mdmId;
        @XmlElement(required = true)
        protected String usernumber;
        @XmlElement(name = "definition_id", required = true)
        protected String definitionId;
        @XmlElement(name = "schedule_frequency", required = true)
        protected String scheduleFrequency;
        @XmlElement(name = "file_data_link", required = true)
        protected String fileDataLink;
        @XmlElement(name = "job_runlog_id", required = true)
        protected String jobRunlogId;
        @XmlElement(name = "legal_name", required = true)
        protected String legalName;
        @XmlElement(required = true)
        protected String isoverwrite;
        @XmlElement(name = "a_content_type", required = true)
        protected String aContentType;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(name = "acl_name", required = true)
        protected String aclName;
        @XmlElement(name = "acl_domain", required = true)
        protected String aclDomain;
        @XmlElement(name = "r_folder_path", required = true)
        protected String rFolderPath;
        @XmlElement(name = "r_object_type", required = true)
        protected String rObjectType;
        @XmlElement(name = "a_status", required = true)
        protected String aStatus;
        @XmlElement(name = "a_last_review_date", required = true)
        protected String aLastReviewDate;
        @XmlElement(name = "r_object_id", required = true)
        protected String rObjectId;
        @XmlElement(name = "file_content_date", required = true)
        protected Date fileContentDate;
        /**
         * Gets the value of the fileContentDate property.
         * 
         * @return
         *     possible object is
         *     {@link Date }
         *     
         */
        public Date getFileContentDate() {
			return fileContentDate;
		}

        /**
         * Sets the value of the fileContentDate property.
         * 
         * @param fileContentDate
         *     allowed object is
         *     {@link Date }
         *     
         */
        public void setFileContentDate(Date fileContentDate) {
			this.fileContentDate = fileContentDate;
		}


		@XmlElement(required = true)
        protected DocumentProperties.DocumentInfo.Keywords keywords;

        public String getFileName() {
			return fileName;
		}

		public void setFileName(String fileName) {
			this.fileName = fileName;
		}


        /**
         * Gets the value of the objectName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjectName() {
            return objectName;
        }

        /**
         * Sets the value of the objectName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjectName(String value) {
            this.objectName = value;
        }

        /**
         * Gets the value of the ownerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOwnerName() {
            return ownerName;
        }

        /**
         * Sets the value of the ownerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOwnerName(String value) {
            this.ownerName = value;
        }

        /**
         * Gets the value of the locale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocale() {
            return locale;
        }

        /**
         * Sets the value of the locale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocale(String value) {
            this.locale = value;
        }

        /**
         * Gets the value of the mdmlevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMdmlevel() {
            return mdmlevel;
        }

        /**
         * Sets the value of the mdmlevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMdmlevel(String value) {
            this.mdmlevel = value;
        }

        /**
         * Gets the value of the mdmId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMdmId() {
            return mdmId;
        }

        /**
         * Sets the value of the mdmId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMdmId(String value) {
            this.mdmId = value;
        }

        /**
         * Gets the value of the usernumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsernumber() {
            return usernumber;
        }

        /**
         * Sets the value of the usernumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsernumber(String value) {
            this.usernumber = value;
        }

        /**
         * Gets the value of the definitionId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefinitionId() {
            return definitionId;
        }

        /**
         * Sets the value of the definitionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefinitionId(String value) {
            this.definitionId = value;
        }

        /**
         * Gets the value of the scheduleFrequency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScheduleFrequency() {
            return scheduleFrequency;
        }

        /**
         * Sets the value of the scheduleFrequency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScheduleFrequency(String value) {
            this.scheduleFrequency = value;
        }

        /**
         * Gets the value of the fileDataLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFileDataLink() {
            return fileDataLink;
        }

        /**
         * Sets the value of the fileDataLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFileDataLink(String value) {
            this.fileDataLink = value;
        }

        /**
         * Gets the value of the jobRunlogId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJobRunlogId() {
            return jobRunlogId;
        }

        /**
         * Sets the value of the jobRunlogId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJobRunlogId(String value) {
            this.jobRunlogId = value;
        }

        /**
         * Gets the value of the legalName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLegalName() {
            return legalName;
        }

        /**
         * Sets the value of the legalName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLegalName(String value) {
            this.legalName = value;
        }

        /**
         * Gets the value of the isoverwrite property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsoverwrite() {
            return isoverwrite;
        }

        /**
         * Sets the value of the isoverwrite property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsoverwrite(String value) {
            this.isoverwrite = value;
        }

        /**
         * Gets the value of the aContentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAContentType() {
            return aContentType;
        }

        /**
         * Sets the value of the aContentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAContentType(String value) {
            this.aContentType = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the aclName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAclName() {
            return aclName;
        }

        /**
         * Sets the value of the aclName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAclName(String value) {
            this.aclName = value;
        }

        /**
         * Gets the value of the aclDomain property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAclDomain() {
            return aclDomain;
        }

        /**
         * Sets the value of the aclDomain property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAclDomain(String value) {
            this.aclDomain = value;
        }

        /**
         * Gets the value of the rFolderPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRFolderPath() {
            return rFolderPath;
        }

        /**
         * Sets the value of the rFolderPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRFolderPath(String value) {
            this.rFolderPath = value;
        }

        /**
         * Gets the value of the rObjectType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRObjectType() {
            return rObjectType;
        }

        /**
         * Sets the value of the rObjectType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRObjectType(String value) {
            this.rObjectType = value;
        }

        /**
         * Gets the value of the aStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAStatus() {
            return aStatus;
        }

        /**
         * Sets the value of the aStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAStatus(String value) {
            this.aStatus = value;
        }

        /**
         * Gets the value of the aLastReviewDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getALastReviewDate() {
            return aLastReviewDate;
        }

        /**
         * Sets the value of the aLastReviewDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setALastReviewDate(String value) {
            this.aLastReviewDate = value;
        }

        /**
         * Gets the value of the rObjectId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRObjectId() {
            return rObjectId;
        }

        /**
         * Sets the value of the rObjectId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRObjectId(String value) {
            this.rObjectId = value;
        }

        /**
         * Gets the value of the keywords property.
         * 
         * @return
         *     possible object is
         *     {@link DocumentProperties.DocumentInfo.Keywords }
         *     
         */
        public DocumentProperties.DocumentInfo.Keywords getKeywords() {
            return keywords;
        }

        /**
         * Sets the value of the keywords property.
         * 
         * @param value
         *     allowed object is
         *     {@link DocumentProperties.DocumentInfo.Keywords }
         *     
         */
        public void setKeywords(DocumentProperties.DocumentInfo.Keywords value) {
            this.keywords = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
         *         &lt;element name="values" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "values"
        })
        public static class Keywords {

            protected List<String> values;

            /**
             * Gets the value of the values property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the values property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getValues().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getValues() {
                if (values == null) {
                    values = new ArrayList<String>();
                }
                return this.values;
            }

        }

    }

}
