//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 12:30:09 PM IST 
//


package com.lexmark.properties.schema.sw.document;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lexmark.properties.schema.sw.document package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lexmark.properties.schema.sw.document
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocumentProperties.DocumentInfo }
     * 
     */
    public DocumentProperties.DocumentInfo createDocumentPropertiesDocumentInfo() {
        return new DocumentProperties.DocumentInfo();
    }

    /**
     * Create an instance of {@link DocumentProperties.DocumentInfo.Keywords }
     * 
     */
    public DocumentProperties.DocumentInfo.Keywords createDocumentPropertiesDocumentInfoKeywords() {
        return new DocumentProperties.DocumentInfo.Keywords();
    }

    /**
     * Create an instance of {@link DocumentProperties }
     * 
     */
    public DocumentProperties createDocumentProperties() {
        return new DocumentProperties();
    }

}
