//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-463 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.28 at 12:14:17 PM IST 
//


package com.lexmark.properties.schema.sw.folder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="folder_info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="r_object_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="source_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="destination_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="r_folder_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="object_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "folderInfo"
})
@XmlRootElement(name = "FolderProperties")
public class FolderProperties {

    @XmlElement(name = "folder_info", required = true)
    protected FolderProperties.FolderInfo folderInfo;

    /**
     * Gets the value of the folderInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FolderProperties.FolderInfo }
     *     
     */
    public FolderProperties.FolderInfo getFolderInfo() {
        return folderInfo;
    }

    /**
     * Sets the value of the folderInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FolderProperties.FolderInfo }
     *     
     */
    public void setFolderInfo(FolderProperties.FolderInfo value) {
        this.folderInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="r_object_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="source_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="destination_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="r_folder_path" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="object_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rObjectId",
        "sourcePath",
        "destinationPath",
        "rFolderPath",
        "objectName"
    })
    public static class FolderInfo {

        @XmlElement(name = "r_object_id", required = true)
        protected String rObjectId;
        @XmlElement(name = "source_path", required = true)
        protected String sourcePath;
        @XmlElement(name = "destination_path", required = true)
        protected String destinationPath;
        @XmlElement(name = "r_folder_path", required = true)
        protected String rFolderPath;
        @XmlElement(name = "object_name", required = true)
        protected String objectName;

        /**
         * Gets the value of the rObjectId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRObjectId() {
            return rObjectId;
        }

        /**
         * Sets the value of the rObjectId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRObjectId(String value) {
            this.rObjectId = value;
        }

        /**
         * Gets the value of the sourcePath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourcePath() {
            return sourcePath;
        }

        /**
         * Sets the value of the sourcePath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourcePath(String value) {
            this.sourcePath = value;
        }

        /**
         * Gets the value of the destinationPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDestinationPath() {
            return destinationPath;
        }

        /**
         * Sets the value of the destinationPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDestinationPath(String value) {
            this.destinationPath = value;
        }

        /**
         * Gets the value of the rFolderPath property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRFolderPath() {
            return rFolderPath;
        }

        /**
         * Sets the value of the rFolderPath property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRFolderPath(String value) {
            this.rFolderPath = value;
        }

        /**
         * Gets the value of the objectName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjectName() {
            return objectName;
        }

        /**
         * Sets the value of the objectName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjectName(String value) {
            this.objectName = value;
        }

    }

}
