
package com.lexmark.schemas.ecm.dctmwebservice.ecmschema._1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DctmWebService", targetNamespace = "http://schemas.lexmark.com/ecm/dctmwebservice/ecmschema/1.0", wsdlLocation = "file:/C:/temp/DctmWebService.wsdl")
public class DctmWebService_Service
    extends Service
{

    private final static URL DCTMWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lexmark.schemas.ecm.dctmwebservice.ecmschema._1.DctmWebService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lexmark.schemas.ecm.dctmwebservice.ecmschema._1.DctmWebService_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/temp/DctmWebService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/temp/DctmWebService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DCTMWEBSERVICE_WSDL_LOCATION = url;
    }

    public DctmWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DctmWebService_Service() {
        super(DCTMWEBSERVICE_WSDL_LOCATION, new QName("http://schemas.lexmark.com/ecm/dctmwebservice/ecmschema/1.0", "DctmWebService"));
    }

    /**
     * 
     * @return
     *     returns DctmWebService
     */
    @WebEndpoint(name = "DctmWebServicePort")
    public DctmWebService getDctmWebServicePort() {
        return super.getPort(new QName("http://schemas.lexmark.com/ecm/dctmwebservice/ecmschema/1.0", "DctmWebServicePort"), DctmWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DctmWebService
     */
    @WebEndpoint(name = "DctmWebServicePort")
    public DctmWebService getDctmWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.lexmark.com/ecm/dctmwebservice/ecmschema/1.0", "DctmWebServicePort"), DctmWebService.class, features);
    }

}
