
package com.lexmark.schemas.ecm.dctmwebservice.ecmschema._1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.2-b05-RC1
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ECMServiceException", targetNamespace = "http://schemas.lexmark.com/ecm/dctmwebservice/ecmschema/1.0")
public class ECMServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ECMServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ECMServiceException_Exception(String message, ECMServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public ECMServiceException_Exception(String message, ECMServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.lexmark.schemas.ecm.dctmwebservice.ecmschema._1.ECMServiceException
     */
    public ECMServiceException getFaultInfo() {
        return faultInfo;
    }

}
