  CREATE TABLE "ROLE" 
   ("ROLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE), 
	"TARGET_PORTAL" VARCHAR2(20 BYTE),
	"ROLE_TYPE" VARCHAR2(20 BYTE),
	 PRIMARY KEY ("ROLE_ID")
  ) ;

  CREATE TABLE "CATEGORY" 
   (	"CATEGORY_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE), 
	"ORDER_NUM" NUMBER(10,0), 
	"TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"IS_DELETED" CHAR(1 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("CATEGORY_ID")
   );
 
  CREATE TABLE "CATEGORY_LOCALE" 
   (	"CATEGORY_LOCALE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE), 
	"SUPPORTED_LOCALE_ID" NUMBER(10,0), 
	"CATEGORY_ID" NUMBER(10,0), 
	 PRIMARY KEY ("CATEGORY_LOCALE_ID")
   );
 
  CREATE TABLE "CONFIGURATION_ITEM" 
   (	"CONFIGURATION_ITEM_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ITEM_KEY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"ITEM_VALUE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("CONFIGURATION_ITEM_ID")
   );
 
  CREATE TABLE "DEFINITION_LOCALE" 
   (	"DEFINITION_LOCALE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"SUPPORTED_LOCALE_ID" NUMBER(10,0), 
	"REPORT_DEFINITION_ID" NUMBER(10,0), 
	 PRIMARY KEY ("DEFINITION_LOCALE_ID")
   );
 
  CREATE TABLE "EMAIL_NOTIFICATION" 
   (	"EMAIL_NOTIFICATION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EMAIL_NAME" VARCHAR2(200 BYTE), 
	"EMAIL_DESCRIPTION" VARCHAR2(500 BYTE), 
	 PRIMARY KEY ("EMAIL_NOTIFICATION_ID")
   );
  CREATE TABLE "EMAIL_NOTIFICATION_LOCALE" 
   (	"EMAIL_NOTIFICATION_LOCALE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EMAIL_SUBJECT" VARCHAR2(200 BYTE), 
	"EMAIL_HEADER" VARCHAR2(2000 BYTE), 
	"EMAIL_BODY" VARCHAR2(4000 BYTE), 
	"EMAIL_FOOTER" VARCHAR2(2000 BYTE), 
	"SUPPORTED_LOCALE_ID" NUMBER(10,0), 
	"EMAIL_NOTIFICATION_ID" NUMBER(10,0), 
	 PRIMARY KEY ("EMAIL_NOTIFICATION_LOCALE_ID")
   );
 
  
  CREATE TABLE "LEXMARKTRANSACTION" 
   (	"LEXMARKTRANSACTION_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"INVOKER" VARCHAR2(150 BYTE), 
	"TARGETSYSTEM" VARCHAR2(100 BYTE), 
	"WEBSERVICENAME" VARCHAR2(100 BYTE), 
	"ACCOUNTID" VARCHAR2(100 BYTE), 
	"LOGINUSER" VARCHAR2(100 BYTE), 
	"STARTTIME" DATE NOT NULL ENABLE, 
	"ENDTIME" DATE NOT NULL ENABLE, 
	"DURATION" NUMBER(19,0), 
	 PRIMARY KEY ("LEXMARKTRANSACTION_ID")
  );
 
  CREATE TABLE "NOTIFICATION" 
   (	"NOTIFICATION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ADMIN_NAME" VARCHAR2(100 BYTE), 
	"DISPLAY_URL" VARCHAR2(250 BYTE), 
	"DISPLAY_ORDER" NUMBER(10,0), 
	"DISPLAY_DATE" DATE, 
	"REMOVE_DATE" DATE, 
	 PRIMARY KEY ("NOTIFICATION_ID")
  ) ;
 
  CREATE TABLE "NOTIFICATION_LOCALE" 
   (	"NOTIFICATION_LOCALE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NOTIFICATION_ID" NUMBER(10,0), 
	"DISPLAY_DESCRIPTION" VARCHAR2(500 BYTE), 
	"SUPPORTED_LOCALE_ID" NUMBER(10,0), 
	 PRIMARY KEY ("NOTIFICATION_LOCALE_ID")
  );
 
  CREATE TABLE "REPORT_ACL" 
   (	"CATEGORY_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ROLE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "FK901BBADF36A7FB95" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ROLE" ("ROLE_ID") ENABLE, 
	 CONSTRAINT "FK901BBADF6DE1922B" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "CATEGORY" ("CATEGORY_ID") ENABLE
   ) ;
 
  CREATE TABLE "REPORT_DEFINITION" 
   (	"REPORT_DEFINITION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DEFINITION_TYPE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE), 
	"MDM_ID" VARCHAR2(100 BYTE), 
	"MDM_LEVEL" VARCHAR2(100 BYTE), 
	"IS_DELETED" CHAR(1 BYTE) NOT NULL ENABLE, 
	"CATEGORY_ID" NUMBER(10,0), 
	"REPORT_TYPE" VARCHAR2(100 BYTE), 
	"REPORT_SOURCE_ID" VARCHAR2(100 BYTE), 
	"IS_MDM" CHAR(1 BYTE), 
	"IS_SCHEDULABLE" CHAR(1 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"VIEW_TYPE" VARCHAR2(16 BYTE) DEFAULT 'ALL' NOT NULL ENABLE, 
	 PRIMARY KEY ("REPORT_DEFINITION_ID"),
 	 CONSTRAINT "FK7850253E6DE1922B" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "CATEGORY" ("CATEGORY_ID") ENABLE
   );
 
  CREATE TABLE "REPORT_DELETE_STATUS" 
   (	"REPORT_DELETE_STATUS_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"R_OBJECT_ID" VARCHAR2(100 CHAR), 
	"IS_DELETED" CHAR(1 CHAR), 
	 PRIMARY KEY ("REPORT_DELETE_STATUS_ID")
  );
 
  CREATE TABLE "REPORT_INSTANCE_PARAMETERS" 
   (	"JOB_RUNLOG_ID" NUMBER(32,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"VALUE" VARCHAR2(255 BYTE),
	 PRIMARY KEY ("JOB_RUNLOG_ID", "NAME")
   )  ;
 
  CREATE TABLE "REPORT_PARAMETER" 
   (	"REPORT_PARAMETER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE), 
	"VALUE" VARCHAR2(100 BYTE), 
	"DEFAULT_VALUES" VARCHAR2(255 BYTE), 
	"DISPLAY_NAME" VARCHAR2(100 BYTE), 
	"DATA_TYPE" VARCHAR2(100 BYTE), 
	"ORDER_NUMBER" NUMBER(10,0) NOT NULL ENABLE, 
	"MAX_SIZE" NUMBER(10,0), 
	"IS_REQUIRED" CHAR(1 BYTE), 
	"REPORT_DEFINITION_ID" NUMBER(10,0), 
	 PRIMARY KEY ("REPORT_PARAMETER_ID")
  ) ;
 
  CREATE TABLE "REPORT_SCHEDULE" 
   (	"REPORT_SCHEDULE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USERNUMBER" VARCHAR2(100 BYTE), 
	"RECEPIENT_EMAIL" VARCHAR2(255 BYTE), 
	"PREFERRED_TIMEZONE" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(255 BYTE), 
	"EMAIL_REMINDER_FLAG" VARCHAR2(1 BYTE), 
	"CUSTOM_LEAD_MINUTES" NUMBER(10,0), 
	"RUN_FREQUENCY" VARCHAR2(1 BYTE), 
	"RUN_INTERVAL" NUMBER(10,0), 
	"SCHEDULE_EFFECTIVE_DATE" DATE, 
	"SCHEDULE_EXPIRATION_DATE" DATE, 
	"DAY_OF_WEEK" NUMBER(10,0), 
	"DAY_OF_MONTH" NUMBER(10,0), 
	"REPORT_DEFINITION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("REPORT_SCHEDULE_ID")
  ) ;
 
  CREATE TABLE "REPORT_SCHEDULE_PARAMETERS" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE), 
	"VALUE" VARCHAR2(255 BYTE), 
	"REPORT_SCHEDULE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("ID"),
   
	 CONSTRAINT "FKE0D80107A38A80FE" FOREIGN KEY ("REPORT_SCHEDULE_ID")
	  REFERENCES "REPORT_SCHEDULE" ("REPORT_SCHEDULE_ID") ENABLE
   );
 

 
  CREATE TABLE "SERVICES_USER" 
   (	"SERVICES_USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USERNUMBER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"RESTRICT_MDM_ID" VARCHAR2(50 BYTE), 
	"RESTRICT_MDM_LEVEL" VARCHAR2(50 BYTE), 
	"CHL_NODE_ID" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("SERVICES_USER_ID")
  ) ;
 
   CREATE TABLE "SUPPORTED_LOCALE" 
   (	"SUPPORTED_LOCALE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SUPPORTED_LOCALE_NAME" VARCHAR2(100 BYTE), 
	"SUPPORTED_LOCALE_CODE" VARCHAR2(100 BYTE), 
	 PRIMARY KEY ("SUPPORTED_LOCALE_ID")
  );
 
  CREATE TABLE "SIEBEL_LOCALIZATION" 
   (	"SIEBEL_LOCALIZATION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OPTION_TYPE" VARCHAR2(50 BYTE), 
	"SIEBEL_VALUE" VARCHAR2(250 BYTE), 
	"SHOW_ENTITLEMENT_FLAG" NUMBER(1,0), 
	"PARTNER_TYPE" VARCHAR2(20 BYTE), 
	"STATUS_ORDER" VARCHAR2(64 CHAR), 
	 PRIMARY KEY ("SIEBEL_LOCALIZATION_ID"),
	 CONSTRAINT "PARTNER_TYPE_CK" CHECK (PARTNER_TYPE IN (NULL, 'DIRECT', 'INDIRECT', 'BOTH')) ENABLE 
  );
 
  CREATE TABLE "SIEBEL_LOCALIZATION_LOCALE" 
   (	"SIEBEL_LOCALIZATION_LOCALE_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DISPLAY_VALUE" VARCHAR2(250 BYTE) NOT NULL ENABLE, 
	"SUPPORTED_LOCALE_ID" NUMBER(10,0), 
	"SIEBEL_LOCALIZATION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	 PRIMARY KEY ("SIEBEL_LOCALIZATION_LOCALE_ID"),
 	 CONSTRAINT "FK5DE80C5B99340AFC" FOREIGN KEY ("SUPPORTED_LOCALE_ID")
	  REFERENCES "SUPPORTED_LOCALE" ("SUPPORTED_LOCALE_ID") ENABLE, 
	 CONSTRAINT "FK5DE80C5B807CEB0A" FOREIGN KEY ("SIEBEL_LOCALIZATION_ID")
	  REFERENCES "SIEBEL_LOCALIZATION" ("SIEBEL_LOCALIZATION_ID") ENABLE
   );
 
  CREATE TABLE "USER_GRID_SETTINGS_ENHANCEMENT"
(
  "USER_NUMBER" VARCHAR2(50 BYTE) NOT NULL ENABLE,
  "GRID_ID"     VARCHAR2(50 BYTE) NOT NULL ENABLE,
  "COLSORDER"   VARCHAR2(200 BYTE),
  "COLSWIDTH"   VARCHAR2(200 BYTE),
  "COLSSORTING" VARCHAR2(200 BYTE),
  "COLSHIDDEN"  VARCHAR2(200 BYTE),
  "COLSFILTER"  VARCHAR2(200 BYTE),
  PRIMARY KEY ("USER_NUMBER", "GRID_ID")
);

  CREATE TABLE "USER_NOTIFICATION_HIDING" 
   (	"NOTIFICATION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 PRIMARY KEY ("NOTIFICATION_ID", "USER_ID")
  );
  
 
     
CREATE TABLE  JOB_RUNLOG (
JOB_RUNLOG_ID	DECIMAL(32,0) NOT NULL,
MDM_ID	VARCHAR2(50),
MDM_LEVEL	VARCHAR2(50),
LEGAL_NAME	VARCHAR2(255),
REPORT_SCHEDULE_ID              	DECIMAL(32,0),
BATCH_ID	VARCHAR2(50),
THREAD_GROUP	NUMBER(10,0) NOT NULL,
OVERDUE_MINUTES NUMBER(10,0),
STATUS_CODE	VARCHAR2(15),
ERROR_LOG	VARCHAR2(500),
RUN_DATE_TIME   DATE DEFAULT sysdate	 NOT NULL,
BUILD_SOURCE	VARCHAR2(32),
BUILD_STARTED_ON	DATE,
BUILD_FINISHED_ON	DATE,
BUILD_STATUS_MSG	VARCHAR2(500),
LOAD_STARTED_ON	DATE,
LOAD_FINISHED_ON	DATE,
LOAD_STATUS_MSG	VARCHAR2(500),
PUBLISHED_ON	DATE,
FILE_TYPE	VARCHAR2(32),
FILE_OBJECT_ID	VARCHAR2(32),
FILE_DATA_LINK	DECIMAL(32,0),
JOB_TYPE	VARCHAR2(25),
RERUN_FLAG	VARCHAR2(1),
FILE_SIZE	NUMBER(10,0),
REPORT_LEADING_DAYS	NUMBER(10,0),
REPORT_TRAILING_DAYS	NUMBER(10,0),
LAST_UPDATED_ON	DATE,
CREATED_BY	VARCHAR2(50)  DEFAULT 'ADMIN' NOT NULL,
CREATED_DT  DATE DEFAULT sysdate  NOT NULL,
UPDATED_BY	VARCHAR2(50),
UPDATED_DT	DATE,
CMD_INVOKED VARCHAR2(2000),
 PRIMARY KEY ("JOB_RUNLOG_ID")
);

CREATE TABLE "JOB_LEADTIME" 
( "TIMEZONE" NUMBER(10,0), 
  "STANDARD_LEAD_MINUTES" NUMBER(32,0),
  PRIMARY KEY ("TIMEZONE")
);
 
-- Sequences 
   
CREATE SEQUENCE  "HIBERNATE_SEQUENCE"  
     MINVALUE 1 
     MAXVALUE 999999999999999999999999999 
     INCREMENT BY 1 
     START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   

CREATE SEQUENCE FILE_DATA_LINK_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    MAXVALUE 9999999999
    NOCYCLE
    CACHE 20
    NOORDER
;

CREATE SEQUENCE JOB_RUNLOG_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    MAXVALUE 9999999999
    NOCYCLE
    CACHE 20
    NOORDER
;

CREATE SEQUENCE JOB_BATCH_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    MAXVALUE 9999999999
    NOCYCLE
    CACHE 20
    NOORDER
;

-- since the PORTAL and SVCSFILE locating at the same database, we do not need create table link, just create a view

---- This function will be referenced by the view, so it needs to be created first
---- R Benzell 
create or replace
FUNCTION jobrun_tooltip_text
(P_JOB_RUNLOG_ID IN number default NULL)
RETURN VARCHAR2
AS
  v_INFO_TEXT Varchar2(32000);
  v_text_max number default  4000;
BEGIN
----Job Level Info
  BEGIN
  Select
    'JobRunLogID: ' || JOB_RUNLOG_ID || chr(13) ||
    'mdmID: ' || MDM_ID || chr(13) ||
    'mdmLevel: ' || MDM_LEVEL || chr(13) ||
    'LegalName: ' || LEGAL_NAME || chr(13) ||
    'usernum: ' || USERNUMBER  || chr(13) ||                                                                                                                                                                                                           
    'recpt email: ' || RECEPIENT_EMAIL || chr(13) ||
    'run freq: ' || RUN_FREQUENCY     || chr(13) ||                                                                                                                                                                                     
    'run interval: ' ||RUN_INTERVAL   || chr(13) ||
    'run date/time:' || to_char(RUN_DATE_TIME,'MM/DD/YYYY HH:MI.SSpm') || ' GMT' || chr(13) ||
    'Dcmnt DateTime: ' || to_char(R_MODIFY_DATE,'MM/DD/YYYY HH:MI.SSpm') || ' GMT' || chr(13) ||
    'Published On: ' || to_char(PUBLISHED_ON,'MM/DD/YYYY HH:MI.SSpm') || ' GMT' || chr(13) ||
    'Job Type:' ||JOB_TYPE      || chr(13) ||                                                                                                                                                                                                          
    'Rerun Flag:' || RERUN_FLAG  || chr(13) ||
    'Status Code: ' || STATUS_CODE || chr(13)
  into v_INFO_TEXT
  From JOB_RUNLOG_DETAILS
  Where JOB_RUNLOG_ID = P_JOB_RUNLOG_ID;
   EXCEPTION
   WHEN OTHERS THEN
      v_INFO_TEXT := v_INFO_TEXT || 'ERROR: JOB_RUNLOG_ID value of: ' || P_JOB_RUNLOG_ID || ' was NOT found in JOB_RUNLOG_DETAILS view!';
END;
----Parameter Info
  For A in
    (select
      PARM_NAME,
      PARM_VALUE
      from JOB_RUNLOG_parms
      where JOB_RUNLOG_ID = P_JOB_RUNLOG_ID)
  Loop
     if length(v_INFO_TEXT) < v_text_max
      then
        v_INFO_TEXT := v_INFO_TEXT ||
           ' * ' || A.PARM_NAME  || ' = ' || A.PARM_VALUE || chr(13) ;
     end if;     
  end loop;
return substr(v_INFO_TEXT,1,v_text_max);
 EXCEPTION
WHEN OTHERS THEN
      v_INFO_TEXT :=  v_INFO_TEXT || 'UNKNOWN ERROR: JOB_RUNLOG_ID value of: ' || P_JOB_RUNLOG_ID || ' was NOT found!';
END;

---- Updated to include function that generates tooltip text 
 CREATE OR REPLACE FORCE VIEW "LGSPORTAL"."LXK_PORTAL_DOC_VIEW" ("SCHEDULE_FREQUENCY", "FILE_DATA_LINK", "USERNUMBER", "LOCALE", "MDM_ID", "MDMLEVEL", "LEGAL_NAME", "JOB_RUNLOG_ID", "DEFINITION_ID", "I_CHRONICLE_ID", "OBJECT_NAME", "I_FULL_FORMAT", "R_FOLDER_PATH", "A_WEBC_URL", "R_OBJECT_ID", "I_CONTENTS_ID", "R_VERSION_LABEL", "CONTENT_ID", "R_MODIFY_DATE", "R_CONTENT_SIZE", "TOOLTIP_TEXT")

AS

  SELECT "SCHEDULE_FREQUENCY",
    "FILE_DATA_LINK",
    "USERNUMBER",
    "LOCALE",
    "MDM_ID",
    "MDMLEVEL",
    "LEGAL_NAME",
    "JOB_RUNLOG_ID",
    "DEFINITION_ID",
    "I_CHRONICLE_ID",
    "OBJECT_NAME",
    "I_FULL_FORMAT",
    "R_FOLDER_PATH",
    "A_WEBC_URL",
    "R_OBJECT_ID",
    "I_CONTENTS_ID",
    "R_VERSION_LABEL",
    "CONTENT_ID",
    "R_MODIFY_DATE",
    "R_CONTENT_SIZE",
    JOBRUN_TOOLTIP_TEXT("JOB_RUNLOG_ID") "TOOLTIP_TEXT"
  FROM SVCSFILE.DCTMPUBLISH_S;
 
 
 
   
   
   ------------------------------------------------------------------------------------
   ---- Below Views are to simply debugging and analysis of the Reports/scheduler engine ---
   ------------------------------------------------------------------------------------
     
     --- JOB_RUNLOG_DETAILS - this view is a join based on JOB_RUNLOG
     --- to just about every table that can be linked in a 1-1 or 1-0 basis
     --- Links to Documentum Published files, if present

CREATE OR REPLACE FORCE VIEW "LGSPORTAL"."JOB_RUNLOG_DETAILS" ("JOB_RUNLOG_ID", "MDM_ID", "MDM_LEVEL", "LEGAL_NAME", "REPORT_SCHEDULE_ID", "USERNUMBER", "RECEPIENT_EMAIL", "PREFERRED_TIMEZONE", "COUNTRY", "EMAIL_REMINDER_FLAG", "CUSTOM_LEAD_MINUTES", "RUN_FREQUENCY", "RUN_INTERVAL", "SCHEDULE_EFFECTIVE_DATE", "SCHEDULE_EXPIRATION_DATE", "DAY_OF_WEEK", "DAY_OF_MONTH", "REPORT_DEFINITION_ID", "DEFINITION_TYPE", "NAME", "IS_DELETED", "CATEGORY_ID", "CATEGORY_NAME", "CATEGORY_TYPE", "REPORT_TYPE", "REPORT_SOURCE_ID", "IS_MDM", "IS_SCHEDULABLE", "DESCRIPTION", "VIEW_TYPE", "BATCH_ID", "THREAD_GROUP", "OVERDUE_MINUTES", "STATUS_CODE", "ERROR_LOG", "RUN_DATE_TIME", "BUILD_SOURCE", "BUILD_STARTED_ON", "BUILD_FINISHED_ON", "BUILD_RUNTIME_SECS", "BUILD_STATUS_MSG", "LOAD_STARTED_ON", "LOAD_FINISHED_ON", "LOAD_STATUS_MSG", "PUBLISHED_ON", "FILE_TYPE", "FILE_OBJECT_ID", "A_WEBC_URL", "OBJECT_NAME", "I_FULL_FORMAT", "R_FOLDER_PATH", "R_MODIFY_DATE", "FILE_DATA_LINK", "JOB_TYPE", "RERUN_FLAG",
  "FILE_SIZE", "REPORT_LEADING_DAYS", "REPORT_TRAILING_DAYS", "LAST_UPDATED_ON", "CREATED_BY", "CREATED_DT", "UPDATED_BY", "UPDATED_DT", "CMD_INVOKED")
AS
  SELECT A.JOB_RUNLOG_ID ,
    A.MDM_ID ,
    A.MDM_LEVEL ,
    A.LEGAL_NAME ,
    A.REPORT_SCHEDULE_ID ,
    B.USERNUMBER,
    B.RECEPIENT_EMAIL,
    B.PREFERRED_TIMEZONE ,
    B.COUNTRY ,
    B.EMAIL_REMINDER_FLAG ,
    B.CUSTOM_LEAD_MINUTES ,
    B.RUN_FREQUENCY,
    B.RUN_INTERVAL,
    B.SCHEDULE_EFFECTIVE_DATE ,
    B.SCHEDULE_EXPIRATION_DATE ,
    B.DAY_OF_WEEK ,
    B.DAY_OF_MONTH ,
    B.REPORT_DEFINITION_ID ,
    C.DEFINITION_TYPE,
    C.NAME,
    C.IS_DELETED ,
    C.CATEGORY_ID ,
    D.NAME,
    D.TYPE,
    C.REPORT_TYPE ,
    C.REPORT_SOURCE_ID,
    C.IS_MDM ,
    C.IS_SCHEDULABLE ,
    C.DESCRIPTION ,
    C.VIEW_TYPE ,
    A.BATCH_ID ,
    A.THREAD_GROUP ,
    A.OVERDUE_MINUTES ,
    A.STATUS_CODE ,
    A.ERROR_LOG ,
    A.RUN_DATE_TIME ,
    A.BUILD_SOURCE ,
    A.BUILD_STARTED_ON ,
    A.BUILD_FINISHED_ON ,
    ROUND(((A.BUILD_FINISHED_ON-A.BUILD_STARTED_ON)*86400),1),
    A.BUILD_STATUS_MSG ,
    A.LOAD_STARTED_ON ,
    A.LOAD_FINISHED_ON ,
    A.LOAD_STATUS_MSG ,
    A.PUBLISHED_ON ,
    A.FILE_TYPE ,
    A.FILE_OBJECT_ID ,
    E.A_WEBC_URL,
    E.OBJECT_NAME,
    E.I_FULL_FORMAT,
    E.R_FOLDER_PATH,
    E.R_MODIFY_DATE,
    A.FILE_DATA_LINK ,
    A.JOB_TYPE ,
    A.RERUN_FLAG ,
    A.FILE_SIZE ,
    A.REPORT_LEADING_DAYS ,
    A.REPORT_TRAILING_DAYS ,
    A.LAST_UPDATED_ON ,
    A.CREATED_BY ,
    A.CREATED_DT ,
    A.UPDATED_BY ,
    A.UPDATED_DT ,
    A.CMD_INVOKED
  FROM JOB_RUNLOG A,
    REPORT_SCHEDULE B,
    REPORT_DEFINITION C,
    CATEGORY D,
    SVCSFILE.DCTMPUBLISH_S E
  WHERE A.REPORT_SCHEDULE_ID = B.REPORT_SCHEDULE_ID (+)
  AND B.REPORT_DEFINITION_ID = C.REPORT_DEFINITION_ID (+)
  AND C.CATEGORY_ID          = D.CATEGORY_ID
  AND A.FILE_OBJECT_ID       = E.R_OBJECT_ID (+)
  ORDER BY A.RUN_DATE_TIME DESC;



-----------------------------------------------------------------------------
---- VIEW_JOB_RUNLOG_DETAILS is a simplified and slightly reorganized subset view
---- of JOB_RUNLOG_DETAILS that focuses on core fields of most value to testers and systems team
---------------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW "LGSPORTAL"."VIEW_JOB_RUNLOG_DETAILS" ("RECEPIENT_EMAIL", "USERNUMBER", "NAME", "A_WEBC_URL", "CATEGORY_NAME", "STATUS_CODE", "ERROR_LOG", "OBJECT_NAME", "BUILD_RUNTIME_SECS", "CREATED_DT", "PUBLISHED_ON", "PREFERRED_TIMEZONE", "IS_DELETED", "DESCRIPTION", "JOB_RUNLOG_ID", "CMD_INVOKED")
AS
  SELECT RECEPIENT_EMAIL,
    USERNUMBER,
    NAME,
    A_WEBC_URL,
    CATEGORY_NAME,
    STATUS_CODE,
    ERROR_LOG,
    OBJECT_NAME,
    BUILD_RUNTIME_SECS,
    CREATED_DT,
    PUBLISHED_ON,
    PREFERRED_TIMEZONE,
    IS_DELETED,
    DESCRIPTION,
    JOB_RUNLOG_ID,
    CMD_INVOKED
  FROM JOB_RUNLOG_DETAILS;



-------------------------------------------------------------------------------
--- JOB_RUNLOG_PARMS.  Similar to JOB_RUNLOG_DETAILS, but denormalized
--- to include all the 1-many Parameters involved with each report invocation
---------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW "LGSPORTAL"."JOB_RUNLOG_PARMS" ("JOB_RUNLOG_ID", "PARM_NAME", "PARM_VALUE", "MDM_ID", "MDM_LEVEL", "LEGAL_NAME", "REPORT_SCHEDULE_ID", "USERNUMBER", "RECEPIENT_EMAIL", "PREFERRED_TIMEZONE", "COUNTRY", "EMAIL_REMINDER_FLAG", "CUSTOM_LEAD_MINUTES", "RUN_FREQUENCY", "RUN_INTERVAL", "SCHEDULE_EFFECTIVE_DATE", "SCHEDULE_EXPIRATION_DATE", "DAY_OF_WEEK", "DAY_OF_MONTH", "REPORT_DEFINITION_ID", "DEFINITION_TYPE", "NAME", "IS_DELETED", "CATEGORY_ID", "CATEGORY_NAME", "CATEGORY_TYPE", "REPORT_TYPE", "REPORT_SOURCE_ID", "IS_MDM", "IS_SCHEDULABLE", "DESCRIPTION", "VIEW_TYPE", "BATCH_ID", "THREAD_GROUP", "OVERDUE_MINUTES", "STATUS_CODE", "ERROR_LOG", "RUN_DATE_TIME", "BUILD_SOURCE", "BUILD_STARTED_ON", "BUILD_FINISHED_ON", "BUILD_STATUS_MSG", "LOAD_STARTED_ON", "LOAD_FINISHED_ON", "LOAD_STATUS_MSG", "PUBLISHED_ON", "FILE_TYPE", "FILE_OBJECT_ID", "A_WEBC_URL", "OBJECT_NAME", "I_FULL_FORMAT", "R_FOLDER_PATH", "FILE_DATA_LINK", "JOB_TYPE", "RERUN_FLAG", "FILE_SIZE",
  "REPORT_LEADING_DAYS", "REPORT_TRAILING_DAYS", "LAST_UPDATED_ON", "CREATED_BY", "CREATED_DT", "UPDATED_BY", "UPDATED_DT", "CMD_INVOKED")
AS
  SELECT A.JOB_RUNLOG_ID ,
    F.NAME,
    F.VALUE,
    A.MDM_ID ,
    A.MDM_LEVEL ,
    A.LEGAL_NAME ,
    A.REPORT_SCHEDULE_ID ,
    B.USERNUMBER,
    B.RECEPIENT_EMAIL,
    B.PREFERRED_TIMEZONE ,
    B.COUNTRY ,
    B.EMAIL_REMINDER_FLAG ,
    B.CUSTOM_LEAD_MINUTES ,
    B.RUN_FREQUENCY,
    B.RUN_INTERVAL,
    B.SCHEDULE_EFFECTIVE_DATE ,
    B.SCHEDULE_EXPIRATION_DATE ,
    B.DAY_OF_WEEK ,
    B.DAY_OF_MONTH ,
    B.REPORT_DEFINITION_ID ,
    C.DEFINITION_TYPE,
    C.NAME,
    C.IS_DELETED ,
    C.CATEGORY_ID ,
    D.NAME,
    D.TYPE,
    C.REPORT_TYPE ,
    C.REPORT_SOURCE_ID,
    C.IS_MDM ,
    C.IS_SCHEDULABLE ,
    C.DESCRIPTION ,
    C.VIEW_TYPE ,
    A.BATCH_ID ,
    A.THREAD_GROUP ,
    A.OVERDUE_MINUTES ,
    A.STATUS_CODE ,
    A.ERROR_LOG ,
    A.RUN_DATE_TIME ,
    A.BUILD_SOURCE ,
    A.BUILD_STARTED_ON ,
    A.BUILD_FINISHED_ON ,
    A.BUILD_STATUS_MSG ,
    A.LOAD_STARTED_ON ,
    A.LOAD_FINISHED_ON ,
    A.LOAD_STATUS_MSG ,
    A.PUBLISHED_ON ,
    A.FILE_TYPE ,
    A.FILE_OBJECT_ID ,
    E.A_WEBC_URL,
    E.OBJECT_NAME,
    E.I_FULL_FORMAT,
    E.R_FOLDER_PATH,
    A.FILE_DATA_LINK ,
    A.JOB_TYPE ,
    A.RERUN_FLAG ,
    A.FILE_SIZE ,
    A.REPORT_LEADING_DAYS ,
    A.REPORT_TRAILING_DAYS ,
    A.LAST_UPDATED_ON ,
    A.CREATED_BY ,
    A.CREATED_DT ,
    A.UPDATED_BY ,
    A.UPDATED_DT ,
    A.CMD_INVOKED
  FROM JOB_RUNLOG A,
    REPORT_SCHEDULE B,
    REPORT_DEFINITION C,
    CATEGORY D,
    SVCSFILE.DCTMPUBLISH_S E,
    REPORT_INSTANCE_PARAMETERS F
  WHERE A.REPORT_SCHEDULE_ID = B.REPORT_SCHEDULE_ID (+)
  AND B.REPORT_DEFINITION_ID = C.REPORT_DEFINITION_ID (+)
  AND C.CATEGORY_ID          = D.CATEGORY_ID
  AND A.FILE_OBJECT_ID       = E.R_OBJECT_ID (+)
  AND A.JOB_RUNLOG_ID        = F.JOB_RUNLOG_ID (+)
  ORDER BY A.JOB_RUNLOG_ID DESC;




-----------------------------------------------------------------------------
---- VIEW_JOB_RUNLOG_PARMS is a simplified and slightly reorganized subset view
---- of JOB_RUNLOG_PARMS that focuses on core fields of most value to systems team and testers
---------------------------------------------------------------------------------
CREATE OR REPLACE FORCE VIEW "LGSPORTAL"."VIEW_JOB_RUNLOG_PARMS" ("RECEPIENT_EMAIL", "USERNUMBER", "NAME", "PARM_NAME", "PARM_VALUE", "CATEGORY_NAME", "STATUS_CODE", "OBJECT_NAME", "CREATED_DT", "JOB_RUNLOG_ID", "CMD_INVOKED")
AS
  SELECT RECEPIENT_EMAIL,
    USERNUMBER,
    NAME,
    PARM_NAME,
    PARM_VALUE,
    CATEGORY_NAME,
    STATUS_CODE,
    OBJECT_NAME,
    CREATED_DT,
    JOB_RUNLOG_ID,
    CMD_INVOKED
  FROM JOB_RUNLOG_PARMS;



   