  CREATE TABLE "OBIEE_REPORT_PARAMETER" 
   (	"REPORT_PARAMETER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CONTACT_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"PARAM_VALUE"  VARCHAR2(400 BYTE),
	"PARAM_VALUE2"  VARCHAR2(400 BYTE),
	 PRIMARY KEY ("REPORT_PARAMETER_ID", "CONTACT_ID")
  );
